# https://developers.home-assistant.io/docs/add-ons/configuration#add-on-config
name: first test
version: "0.0.1"
slug: example
description: First test
url: "https://github.com/daestx/addons-example"
arch:
  - armhf
  - armv7
  - aarch64
  - amd64
  - i386
init: false
map:
  - share:rw
options:
  message: "Hello world..."
schema:
  message: "str?"
image: "ghcr.io/home-assistant/{arch}-addon-example"
