# https://developers.home-assistant.io/docs/add-ons/configuration#add-on-config
name: Raise3D
version: "0.0.2"
slug: example
description: Raise3D 3D printer support
url: "https://github.com/daestx/raise3d"
arch:
  - armhf
  - armv7
  - aarch64
  - amd64
  - i386
init: false
map:
  - share:rw
options:
  IP: ""
  Port: "10800"
  Password: ""
schema:
  IP: "str?"
  Port: "str?"
  Password: "str?"
#image: "ghcr.io/home-assistant/{arch}-raise3d"
